Repository gyselax/gyselalibxx, pull requests merged in 2025-05, with the labels that each got.

#269 Add a 3D inverse operator
  src/math_tools/math_tools.hpp
  tests/math_tools/test_math_tools.cpp
Labels: Ready to merge

#270 Improve `CombinedMapping`
  src/mapping/cartesian_to_circular.hpp
  src/mapping/cartesian_to_czarny.hpp
  src/mapping/circular_to_cartesian.hpp
  src/mapping/combined_mapping.hpp
  src/mapping/cylindrical_to_cartesian.hpp
  src/mapping/czarny_to_cartesian.hpp
  src/mapping/inv_jacobian_o_point.hpp
  tests/mapping/geometry_mapping_tests.hpp
  tests/mapping/metric_tensor_evaluator.cpp
Labels: Ready to merge

#277 Rename fdistribu -> density in r,theta geometry
  src/geometryRTheta/poisson/iqnsolver.hpp
  src/geometryRTheta/time_solver/bsl_predcorr.hpp
  src/geometryRTheta/time_solver/bsl_predcorr_second_order_explicit.hpp
  src/geometryRTheta/time_solver/bsl_predcorr_second_order_implicit.hpp
  src/geometryRTheta/time_solver/itimesolver.hpp
  tests/geometryRTheta/advection_field_rtheta/advection_field_gtest.cpp
  tests/geometryRTheta/advection_rtheta/advection_simulation_utils.hpp
Labels: Ready to merge

#274 Improve docker build trigger
  .github/actions/changed_files/action.yml
  .github/actions/docker_update/action.yml
  .github/actions/duplicate_check/action.yml
  .github/actions/test_filter/action.yml
  .github/workflows/cpu_tests.yml
  .github/workflows/deploy.yml
  .github/workflows/gpu_tests.yml
  .github/workflows/static_analyses.yml
Labels: Ready to review, Ready to merge

#280 Fix test to handle rounding errors
  tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp
Labels: Ready to merge

#275 Add a compilation with clang
  .github/workflows/cpu_tests.yml
  .gitlab-ci.yml
  docker/gyselalibxx_env/Dockerfile
  src/advection/bsl_advection_1d.hpp
  src/interpolation/spline_interpolator.hpp
  src/interpolation/spline_interpolator_2d.hpp
  src/math_tools/ipartial_derivative.hpp
  src/math_tools/spline_1d_partial_derivative.hpp
  src/math_tools/spline_builder_2d_cache.hpp
  src/multipatch/spline/multipatch_spline_builder.hpp
  src/multipatch/spline/multipatch_spline_builder_2d.hpp
  src/pde_solvers/fem_1d_poisson_solver.hpp
  src/pde_solvers/polarpoissonlikesolver.hpp
  tests/geometryRTheta/advection_field_rtheta/test_cases_adv_field.hpp
  tests/geometryRTheta/advection_rtheta/test_cases.hpp
  tests/interpolation/polar_splines.cpp
Labels: Ready to review, Ready to merge

#283 Add constexpr identity tensor
  src/data_types/static_tensors.hpp
  tests/data_types/tensor.cpp
Labels: Ready to merge

#293 Update gyselalib URLs in installation guide
  docs/first_steps/install.md
Labels: documentation, Ready to merge

#286 Allow overloaded functions in coordinate convertor classes
  src/mapping/circular_to_cartesian.hpp
  src/mapping/mapping_tools.hpp
Labels: Ready to merge

#239 Add a Lie-Poisson bracket operator
  .github/actions/changed_files/action.yml
  bin/pre-commit
  src/mapping/metric_tensor_evaluator.hpp
  src/mapping/toroidal_to_cylindrical.hpp
  src/math_tools/gradient.hpp
  src/math_tools/lie_poisson_bracket.hpp
  tests/mapping/geometry_mapping_tests.hpp
  tests/math_tools/CMakeLists.txt
  tests/math_tools/test_poisson_bracket.cpp
Labels: Ready to review

#294 Add a ConstantPartialDerivative calculator
  src/math_tools/central_fdm_partial_derivatives.hpp
  src/math_tools/central_fdm_partial_derivatives_with_boundary_values.hpp
  src/math_tools/constant_partial_derivatives.hpp
  tests/math_tools/test_partial_derivatives.cpp
Labels: Ready to review, Ready to merge

#302 Add an identity mapping for testing
  src/data_types/tensor.hpp
  src/mapping/identity_coordinate_change.hpp
  src/utils/ddc_helper.hpp
  tests/mapping/mapping_static_properties.cpp
Labels: Ready to review, Ready to merge

#306 Clean mapping interface
  src/geometryRTheta/advection_field/advection_field_rtheta.hpp
  src/mapping/cartesian_to_circular.hpp
  src/mapping/cartesian_to_cylindrical.hpp
  src/mapping/circular_to_cartesian.hpp
  src/mapping/combined_mapping.hpp
  src/mapping/cylindrical_to_cartesian.hpp
  src/mapping/czarny_to_cartesian.hpp
  src/mapping/discrete_to_cartesian.hpp
  src/mapping/identity_coordinate_change.hpp
  src/mapping/inverse_jacobian_matrix.hpp
  src/mapping/mapping_tools.hpp
  src/mapping/metric_tensor_evaluator.hpp
  src/mapping/toroidal_to_cylindrical.hpp
  src/mapping/vector_mapper.hpp
  src/pde_solvers/polarpoissonlikesolver.hpp
  src/quadrature/volume_quadrature_nd.hpp
  tests/geometryRTheta/polar_poisson/test_cases.hpp
  tests/mapping/mapping_jacobian.cpp
  tests/mapping/mapping_jacobian_matrix_coef.cpp
  tests/mapping/mapping_static_properties.cpp
  tests/mapping/refined_discrete_mapping.cpp
Labels: Ready to merge

#310 Rename mapping to coordinate transformations
  src/CMakeLists.txt
  src/README.md
  src/advection/spline_polar_foot_finder.hpp
  src/coord_transformations/CMakeLists.txt
  src/coord_transformations/README.md
  src/coord_transformations/barycentric_to_cartesian.hpp
  src/coord_transformations/cartesian_to_barycentric.hpp
  src/coord_transformations/cartesian_to_circular.hpp
  src/coord_transformations/cartesian_to_cylindrical.hpp
  src/coord_transformations/cartesian_to_czarny.hpp
  src/coord_transformations/circular_to_cartesian.hpp
  src/coord_transformations/combined_mapping.hpp
  src/coord_transformations/coord_transformation_tools.hpp
  src/coord_transformations/cylindrical_to_cartesian.hpp
  src/coord_transformations/czarny_to_cartesian.hpp
  src/coord_transformations/discrete_mapping_builder.hpp
  src/coord_transformations/discrete_to_cartesian.hpp
  src/coord_transformations/geometry_pseudo_cartesian.hpp
  src/coord_transformations/identity_coordinate_change.hpp
  src/coord_transformations/inv_jacobian_o_point.hpp
  src/coord_transformations/inverse_jacobian_matrix.hpp
  src/coord_transformations/metric_tensor_evaluator.hpp
  src/coord_transformations/toroidal_to_cylindrical.hpp
  src/coord_transformations/vector_mapper.hpp
  src/geometryRTheta/advection_field/CMakeLists.txt
  src/interpolation/polar_splines/CMakeLists.txt
  src/interpolation/polar_splines/polar_bsplines.hpp
  src/mapping/CMakeLists.txt
  src/multipatch/connectivity/CMakeLists.txt
  src/multipatch/connectivity/onion_patch_locator.hpp
  src/pde_solvers/CMakeLists.txt
  src/pde_solvers/polarpoissonlikesolver.hpp
  src/quadrature/CMakeLists.txt
  src/quadrature/volume_quadrature_nd.hpp
  tests/CMakeLists.txt
  tests/coord_transformations/CMakeLists.txt
  tests/coord_transformations/analytical_inverse.cpp
  tests/coord_transformations/coord_transformations_execution_space_access.cpp
  tests/coord_transformations/coord_transformations_static_properties.cpp
  tests/coord_transformations/coord_transformations_testing_tools.hpp
  tests/coord_transformations/geometry_coord_transformations_tests.hpp
  tests/coord_transformations/jacobian.cpp
  tests/coord_transformations/jacobian_matrix_coef.cpp
  tests/coord_transformations/metric_tensor_evaluator.cpp
  tests/coord_transformations/pseudo_cartesian_jacobian_matrix.cpp
  tests/coord_transformations/refined_discrete_mapping.cpp
  tests/interpolation/bernstein.cpp
  tests/mapping/CMakeLists.txt
  tests/math_tools/CMakeLists.txt
  tests/math_tools/test_gradient.cpp
  tests/math_tools/test_math_tools.cpp
  tests/math_tools/test_poisson_bracket.cpp
Labels: Ready to review

#312 Improve installation docs
  .github/workflows/cpu_tests.yml
  .gitlab-ci.yml
  README.md
  docs/first_steps/install.md
  docs/first_steps/landau_damping_tutorial.md
  docs/mkdocs.yml
  docs/prepare_mkdocs.py
  docs/requirements.txt
  docs/stylesheets/extra.css
  toolchains/README.md
  toolchains/a100.leonardo.spack/toolchain.cmake
  toolchains/common_toolchains/ci_coverage_toolchain.cmake
  toolchains/common_toolchains/importable_defaults.cmake
  toolchains/common_toolchains/openmp_release_toolchain.cmake
  toolchains/common_toolchains/serial_debug_toolchain.cmake
  toolchains/common_toolchains/serial_release_toolchain.cmake
  toolchains/cpu.spack.gyselalibxx_env/toolchain.cmake
  toolchains/v100.persee/gpu_debug.cmake
  toolchains/v100.persee/toolchain.cmake
  toolchains/v100.ruche/toolchain.cmake
  toolchains/xeon.persee/debug_toolchain.cmake
  toolchains/xeon.persee/environment.sh
  toolchains/xeon.persee/toolchain.cmake
Labels: Ready to merge

#315 Remove calls to deprecated `Kokkos::View::stride_N` functions
  src/matrix_tools/matrix_utils.hpp
Labels: Ready to merge

#314 Update License file
  LICENSE
Labels: Ready to review, Ready to merge

#313 Update AUTHORS file
  AUTHORS
Labels: Ready to review, Ready to merge

#308 Add a method to change vector space
  src/advection/spline_polar_foot_finder.hpp
  src/coord_transformations/vector_mapper.hpp
  src/data_types/vector_index_tools.hpp
  src/utils/type_seq_tools.hpp
  tests/coord_transformations/CMakeLists.txt
  tests/coord_transformations/vector_basis_change.cpp
Labels: Ready to merge

#311 Prepare for v0.1.0
  .github/pull_request_template.md
  .github/workflows/release.yml
  .github/workflows/release_candidate.yml
  .github/workflows/static_analyses.yml
  .gitlab/merge_request_templates/default.md
  CHANGELOG.md
  CMakeLists.txt
  src/collisions/README.md
  src/version.txt
Labels: Ready to merge

#318 Add documentation about tensor implementation
  docs/mkdocs.yml
  docs/standards/coding_covariant_and_contravariant_tensors.md
Labels: documentation, Ready to review, Ready to merge

#321 Update coding conventions file
  CHANGELOG.md
  bin/ci_tools/gyselalib_static_analysis.py
  docs/standards/CODING_STANDARD.md
  src/data_types/README.md
  src/interpolation/polar_splines/polar_bsplines.hpp
  src/interpolation/polar_splines/polar_spline_evaluator.hpp
  src/io/input.hpp
  src/math_tools/l_norm_tools.hpp
  tests/interpolation/polar_spline_create_mirror.cpp
Labels: documentation, Ready to merge

#324 Fix cmake in submodule
  CHANGELOG.md
  CMakeLists.txt
Labels: Ready to review, Ready to merge, packaging
