Repository gyselax/gyselalibxx, pull requests merged in 2025-08, with the labels that each got.

#397 Clean up `bsl_predcorr_second_order_explicit.hpp` in geometryRTheta
  CHANGELOG.md
  src/geometryRTheta/time_solver/bsl_predcorr_second_order_explicit.hpp
Labels: Ready to merge

#400 Add types for MultipatchType
  CHANGELOG.md
  src/data_types/derivative_field_common.hpp
  src/multipatch/data_types/types.hpp
Labels: Ready to merge

#404 Fix bad copies in r,theta simulations
  CHANGELOG.md
  simulations/geometryRTheta/diocotron/diocotron.cpp
  simulations/geometryRTheta/vortex_merger/vortex_merger.cpp
Labels: Ready to review, Ready to merge

#390 Adastra toolchain: install the Kokkos ecosystem with Spack
  CHANGELOG.md
  toolchains/mi250.hipcc.adastra.spack/environment.sh
  toolchains/mi250.hipcc.adastra.spack/gyselalibxx-spack-environment.yaml
  toolchains/mi250.hipcc.adastra.spack/prepare.sh
  toolchains/mi250.hipcc.adastra.spack/toolchain.cmake
Labels: Ready to review

#407 Add a profiling tutorial to the documentation
  docs/first_steps/profiling.md
  docs/mkdocs.yml
Labels: documentation, Ready to merge, JOSS

#410 Fix some pedantic warnings
  tests/advection/1d_advection_x.cpp
  tests/advection/1d_advection_xvx.cpp
  tests/advection/1d_advection_xyvxvy.cpp
Labels: Ready to merge

#413 Fix typos in docs
  docs/standards/coding_covariant_and_contravariant_tensors.md
Labels: documentation, Ready to review

#411 Use Spack to install the Kokkos ecosystem in the GENOA Adastra toolchain
  CHANGELOG.md
  toolchains/genoa.gcc.adastra.spack/environment.sh
  toolchains/genoa.gcc.adastra.spack/gyselalibxx-spack-environment.yaml
  toolchains/genoa.gcc.adastra.spack/prepare.sh
  toolchains/genoa.gcc.adastra.spack/toolchain.cmake
  toolchains/mi250.hipcc.adastra.spack/prepare.sh
Labels: Ready to merge

#415 Update .typos.toml
  .typos.toml
Labels: Ready to review, Ready to merge

#414 Add curl operator
  CHANGELOG.md
  src/math_tools/curl.hpp
  tests/math_tools/CMakeLists.txt
  tests/math_tools/test_curl.cpp
Labels: Ready to merge
