Repository gyselax/gyselalibxx, pull requests merged in 2025-07, with the labels that each got.

#353 Remove unnecessary std::move
  CHANGELOG.md
  src/matrix_tools/matrix_batch_csr.hpp
  src/multipatch/data_types/multipatch_field.hpp
  src/multipatch/data_types/multipatch_field_mem.hpp
Labels: Ready to review, Ready to merge

#357 Add debugging docs
  .typos.toml
  docs/mkdocs.yml
  docs/troubleshooting/Common_compilation_problems.md
  docs/troubleshooting/Debugging_workflow.md
Labels: documentation, Ready to review, Ready to merge

#359 Add a PDI output for VectorFields
  CHANGELOG.md
  src/io/CMakeLists.txt
  src/io/README.md
  src/io/pdi_helper.hpp
  tests/CMakeLists.txt
  tests/io/CMakeLists.txt
  tests/io/test_pdi.cpp
Labels: Ready to review, Ready to merge

#364 Add decision tree for GitHub vs GitLab
  docs/development/developer_FAQ.md
  docs/images/gitlab_or_github.png
Labels: Ready to merge

#377 Fix Ruche modules
  CHANGELOG.md
  toolchains/v100.ruche/environment.sh
Labels: Ready to merge

#336 Enable SYSTEM in cmake add_subdirectory
  CHANGELOG.md
  CMakeLists.txt
Labels: Ready to review, Ready to merge

#355 Remove `PolarSpline` type
  CHANGELOG.md
  src/geometryRTheta/advection_field/advection_field_rtheta.hpp
  src/geometryRTheta/geometry/README.md
  src/geometryRTheta/geometry/geometry.hpp
  src/geometryRTheta/time_solver/bsl_predcorr.hpp
  src/geometryRTheta/time_solver/bsl_predcorr_second_order_explicit.hpp
  src/geometryRTheta/time_solver/bsl_predcorr_second_order_implicit.hpp
  src/interpolation/polar_splines/polar_bsplines.hpp
  src/interpolation/polar_splines/polar_spline.hpp
  src/interpolation/polar_splines/polar_spline_evaluator.hpp
  src/pde_solvers/polarpoissonlikesolver.hpp
  tests/geometryRTheta/advection_field_rtheta/test_cases_adv_field.hpp
  tests/geometryRTheta/advection_rtheta/advection_all_tests.cpp
  tests/geometryRTheta/advection_rtheta/advection_selected_test.cpp
  tests/geometryRTheta/advection_rtheta/advection_simulation_utils.hpp
  tests/interpolation/CMakeLists.txt
  tests/interpolation/polar_spline_create_mirror.cpp
  tests/interpolation/polar_splines.cpp
Labels: Ready to merge

#382 Uniformise toolchains
  CHANGELOG.md
  toolchains/a100.leonardo.spack/environment.sh
  toolchains/a100.leonardo.spack/prepare.sh
  toolchains/a100.leonardo.spack/toolchain.cmake
  toolchains/common_toolchains/ci_coverage_toolchain.cmake
  toolchains/common_toolchains/openmp_release_toolchain.cmake
  toolchains/common_toolchains/serial_debug_toolchain.cmake
  toolchains/common_toolchains/serial_release_toolchain.cmake
  toolchains/cpu.spack.gyselalibxx_env/toolchain.cmake
  toolchains/docker.gyselalibxx_env/environment.sh
  toolchains/genoa.gcc.adastra.spack/environment.sh
  toolchains/genoa.gcc.adastra.spack/toolchain.cmake
  toolchains/mi250.hipcc.adastra.spack/environment.sh
  toolchains/mi250.hipcc.adastra.spack/toolchain.cmake
  toolchains/v100.persee/environment.sh
  toolchains/v100.persee/gpu_debug.cmake
  toolchains/v100.persee/toolchain.cmake
  toolchains/v100.ruche/environment.sh
  toolchains/v100.ruche/toolchain.cmake
  toolchains/xeon.persee/environment.sh
  toolchains/xeon.persee/toolchain.cmake
Labels: Ready to review

#386 Improve matrix handling for polar poisson solver
  CHANGELOG.md
  src/matrix_tools/matrix_batch_csr.hpp
  src/matrix_tools/matrix_utils.hpp
  src/pde_solvers/polarpoissonlikesolver.hpp
Labels: Ready to merge

#389 Simplify polar bspline usage
  src/interpolation/polar_splines/polar_bsplines.hpp
  src/interpolation/polar_splines/polar_spline_evaluator.hpp
Labels: Ready to merge

#388 Calculate polar bspline on the fly in PolarSplineFEMPoissonLikeSolver
  CHANGELOG.md
  src/interpolation/polar_splines/polar_bsplines.hpp
  src/pde_solvers/polarpoissonlikesolver.hpp
  tests/geometryRTheta/polar_poisson/test_poisson.py
Labels: Ready to review, Blocked

#391 Remove `uid()` calls in `PolarSplineFEMPoissonLikeSolver`
  CHANGELOG.md
  src/pde_solvers/polarpoissonlikesolver.hpp
Labels: Ready to merge
