Repository gyselax/gyselalibxx, pull requests merged in 2025-03, with the labels that each got.

#144 Correct definition of r_extent and theta_extent in collision operator
  src/collisions/collision_common_configuration.hpp
  src/collisions/collision_operator.cpp
Labels: bug, Ready to review

#152 Correct the definition of norm_inf
  src/math_tools/l_norm_tools.hpp
Labels: Ready to merge

#153 Rename VOICEXX->GYSELALIBXX
  .github/workflows/static_analyses.yml
  CMakeLists.txt
  bin/persee-spack-setup
  post-process/PythonScripts/READutils.py
  post-process/PythonScripts/gysdata/data_structure_RTheta.yaml
  post-process/PythonScripts/gysdata/data_structure_XVx.yaml
  post-process/PythonScripts/gysdata/data_structure_XY.yaml
  post-process/PythonScripts/gysdata/data_structure_XYVxVy.yaml
  post-process/PythonScripts/gysdata/data_structure_neutral.yaml
  post-process/PythonScripts/gysdata/data_structure_sheath.yaml
  simulations/geometryRTheta/diocotron/pdi_out.yml.hpp
  simulations/geometryRTheta/vortex_merger/pdi_out.yml.hpp
  simulations/geometryXVx/bump_on_tail/bumpontail_fem_uniform.cpp
  simulations/geometryXVx/bump_on_tail/bumpontail_fft.cpp
  simulations/geometryXVx/bump_on_tail/pdi_out.yml.hpp
  simulations/geometryXVx/landau/landau_fem_uniform.cpp
  simulations/geometryXVx/landau/landau_fft.cpp
  simulations/geometryXVx/landau/pdi_out.yml.hpp
  simulations/geometryXY/guiding_centre/pdi_out.yml.hpp
  simulations/geometryXYVxVy/landau/landau4d_fft.cpp
  simulations/geometryXYVxVy/landau/pdi_out.yml.hpp
  src/io/input.cpp
  src/io/input.hpp
  src/io/pdi_helper.hpp
  src/speciesinfo/species_init.cpp
  src/speciesinfo/species_init.hpp
  tests/geometryRTheta/advection_rtheta/advection_all_tests.cpp
  tests/geometryRTheta/advection_rtheta/advection_selected_test.cpp
  tests/geometryRTheta/polar_poisson/polarpoissonfemsolver.cpp
  tests/geometryRTheta/spline_interpolator_rtheta/spline_interpolator_rtheta.cpp
  tests/geometryXVx/bump_on_tail/test_bumpontail.sh
  tests/geometryXVx/bump_on_tail/test_bumpontail_restart.sh
  tests/geometryXVx/landau/test_landau.sh
  tests/geometryXVx/landau/test_landau_restart.sh
  tests/geometryXYVxVy/landau/test_landau4d.sh
  tests/geometryXYVxVy/landau/test_landau4d_small.sh
  toolchains/a100.leonardo.spack/toolchain.cmake
  toolchains/v100.persee/toolchain.cmake
  toolchains/v100.ruche/toolchain.cmake
Labels: Ready to merge

#114 Add a tensor_mul operator
  ci_tools/gyselalib_static_analysis.py
  src/data_types/indexed_tensor.hpp
  src/data_types/tensor.hpp
  src/data_types/tensor_index_tools.hpp
  src/data_types/vector_index_tools.hpp
  src/utils/type_seq_tools.hpp
  tests/data_types/tensor.cpp
Labels: Ready to merge

#161 Remove unnecessary NDTag and replace with VectorIndexSet
  simulations/geometryXY/guiding_centre/guiding_centre.cpp
  src/advection/ipolar_foot_finder.hpp
  src/advection/spline_polar_foot_finder.hpp
  src/data_types/vector_field.hpp
  src/data_types/vector_field_mem.hpp
  src/geometryRTheta/advection/bsl_advection_rtheta.hpp
  src/geometryRTheta/advection_field/advection_field_rtheta.hpp
  src/geometryRTheta/geometry/README.md
  src/geometryRTheta/geometry/geometry.hpp
  src/geometryXY/geometry/README.md
  src/geometryXY/geometry/geometry.hpp
  src/geometryXY/time_integration/predcorr_RK2.hpp
  src/geometryXYVxVy/poisson/qnsolver.cpp
  src/mapping/vector_mapper.hpp
  src/math_tools/l_norm_tools.hpp
  src/multipatch/data_types/types.hpp
  src/pde_solvers/fft_poisson_solver.hpp
  src/utils/README.md
  src/utils/directional_tag.hpp
  tests/data_types/deriv_field.cpp
  tests/data_types/device_host_t.cpp
  tests/data_types/field.cpp
  tests/geometryRTheta/advection_rtheta/advection_all_tests.cpp
  tests/geometryRTheta/advection_rtheta/advection_simulation_utils.hpp
  tests/math_tools/test_lnorm_tools.cpp
  tests/multipatch/spline/multipatch_spline_builder.cpp
  tests/multipatch/spline/multipatch_spline_builder_2d.cpp
  tests/pde_solvers/fftpoissonsolver.cpp
  tests/timestepper/crank_nicolson_2d_mixed.cpp
  tests/timestepper/euler_2d_mixed.cpp
  tests/timestepper/runge_kutta_2d.cpp
  tests/timestepper/runge_kutta_2d_mixed.cpp
Labels: Ready to review

#154 Update adastra toolchain's prepare.sh
  toolchains/mi250.hipcc.adastra.spack/environment.sh
  toolchains/mi250.hipcc.adastra.spack/prepare.sh
Labels: bug, Ready to merge

#162 Generalise interpolation rtheta
  simulations/geometryRTheta/diocotron/CMakeLists.txt
  simulations/geometryRTheta/diocotron/diocotron.cpp
  simulations/geometryRTheta/vortex_merger/CMakeLists.txt
  simulations/geometryRTheta/vortex_merger/vortex_merger.cpp
  src/geometryRTheta/CMakeLists.txt
  src/geometryRTheta/README.md
  src/geometryRTheta/advection/CMakeLists.txt
  src/geometryRTheta/advection/bsl_advection_rtheta.hpp
  src/geometryRTheta/interpolation/CMakeLists.txt
  src/geometryRTheta/interpolation/README.md
  src/geometryRTheta/interpolation/i_interpolator_rtheta.hpp
  src/geometryRTheta/interpolation/spline_interpolator_rtheta.hpp
  src/geometryRTheta/poisson/CMakeLists.txt
  src/geometryRTheta/poisson/poisson_like_rhs_function.hpp
  src/geometryRTheta/time_solver/CMakeLists.txt
  src/geometryRTheta/time_solver/bsl_predcorr.hpp
  src/geometryRTheta/time_solver/bsl_predcorr_second_order_explicit.hpp
  src/geometryRTheta/time_solver/bsl_predcorr_second_order_implicit.hpp
  src/interpolation/README.md
  src/interpolation/i_interpolator_2d.hpp
  src/interpolation/spline_interpolator_2d.hpp
  tests/geometryRTheta/advection_field_rtheta/CMakeLists.txt
  tests/geometryRTheta/advection_field_rtheta/advection_field_gtest.cpp
  tests/geometryRTheta/advection_field_rtheta/test_cases_adv_field.hpp
  tests/geometryRTheta/advection_rtheta/CMakeLists.txt
  tests/geometryRTheta/advection_rtheta/advection_all_tests.cpp
  tests/geometryRTheta/advection_rtheta/advection_selected_test.cpp
  tests/geometryRTheta/advection_rtheta/advection_simulation_utils.hpp
  tests/geometryRTheta/advection_rtheta/test_cases.hpp
  tests/geometryRTheta/spline_interpolator_rtheta/CMakeLists.txt
  tests/geometryRTheta/spline_interpolator_rtheta/spline_interpolator_rtheta.cpp
Labels: Ready to merge

#164 Add a cache class for storing spline coefficients from a spline builder
  src/math_tools/spline_builder_2d_cache.hpp
  tests/math_tools/CMakeLists.txt
  tests/math_tools/test_spline_2d_cache.cpp
Labels: Ready to merge

#168 Minor tensor improvements
  src/data_types/indexed_tensor.hpp
  src/data_types/tensor.hpp
Labels: Ready to merge

#169 Reduce duplication in mapping tests
  tests/mapping/geometry_mapping_tests.hpp
  tests/mapping/mapping_execution_space_access.cpp
  tests/mapping/mapping_jacobian.cpp
  tests/mapping/mapping_jacobian_matrix_coef.cpp
  tests/mapping/metric_tensor_evaluator.cpp
  tests/mapping/refined_discrete_mapping.cpp
Labels: Ready to merge

#174 Improve `tensor_mul` static assertions
  src/data_types/indexed_tensor.hpp
  src/data_types/tensor_index_tools.hpp
  tests/data_types/CMakeLists.txt
  tests/data_types/geometry_tensor.hpp
  tests/data_types/static_assert_tests/CMakeLists.txt
  tests/data_types/static_assert_tests/tensor_mul_3_indices.cpp
  tests/data_types/static_assert_tests/tensor_mul_contra_contra.cpp
  tests/data_types/static_assert_tests/tensor_mul_cov_cov.cpp
  tests/data_types/static_assert_tests/tensor_mul_incompatible_index_set.cpp
  tests/data_types/static_assert_tests/tensor_mul_multiple_types.cpp
  tests/data_types/static_assert_tests/tensor_mul_wrong_index.cpp
  tests/data_types/tensor.cpp
Labels: bug

#179 Remove the misleading `to_covariant` method
  src/mapping/metric_tensor_evaluator.hpp
  src/pde_solvers/polarpoissonlikesolver.hpp
Labels: Ready to merge

#180 Add citation generation file
  CITATION.cff
Labels: documentation, Ready to merge

#167 Update Spline1DPartialDerivative class and create Spline1DPartialDerivativeCreator
  src/math_tools/README.md
  src/math_tools/central_fdm_partial_derivatives.hpp
  src/math_tools/ipartial_derivative.hpp
  src/math_tools/ipartial_derivatives.hpp
  src/math_tools/spline_1d_partial_derivative.hpp
  src/math_tools/spline_partial_derivatives_1d.hpp
  tests/math_tools/test_partial_derivatives.cpp
Labels: Ready to merge

#181 Adding documentation about curvilinear coordinates
  docs/curvilinear_coordinates_contravariant_covariant_bases.png
  docs/curvilinear_coordinates_def.png
  docs/mathematical_and_physical_conventions.md
Labels: Ready to merge

#185 Use allfdistribu_predicted in bsl_predcorr_second_order_implicit.hpp
  src/geometryRTheta/time_solver/bsl_predcorr_second_order_implicit.hpp
Labels: Ready to merge

#189 Improve terminology in advection field docs
  src/geometryRTheta/advection/README.md
  src/geometryRTheta/advection/bsl_advection_rtheta.hpp
  src/geometryRTheta/advection_field/advection_field_rtheta.hpp
  tests/geometryRTheta/advection_field_rtheta/test_cases_adv_field.hpp
  tests/geometryRTheta/advection_rtheta/README.md
Labels: documentation, Ready to merge

#190 Add explanations of the notation used for characteristics
  src/advection/README.md
Labels: documentation

#191 Improve the readability of the markdown linter
  ci_tools/markdown_linter.py
Labels: documentation, Ready to review

#178 Fix definition of the advection field on RTheta
  src/geometryRTheta/advection/README.md
  src/geometryRTheta/advection/bsl_advection_rtheta.hpp
  src/geometryRTheta/advection/iadvection_rtheta.hpp
  src/geometryRTheta/advection_field/README.md
  src/geometryRTheta/advection_field/advection_field_rtheta.hpp
  tests/geometryRTheta/advection_field_rtheta/advection_field_gtest.cpp
  tests/geometryRTheta/advection_field_rtheta/test_cases_adv_field.hpp
  tests/geometryRTheta/advection_rtheta/README.md
Labels: Ready to merge

#192 Adding the `maximum_distance_between_adjacent_points` function in ddcHelper namespace
  src/utils/ddc_helper.hpp
  tests/utils/test_ddcHelpers.cpp
Labels: Ready to merge

#195 Express metric tensor on correct basis
  src/geometryRTheta/advection_field/advection_field_rtheta.hpp
  src/mapping/metric_tensor_evaluator.hpp
  src/pde_solvers/polarpoissonlikesolver.hpp
Labels: Ready to merge

#194 Fix documentation on bare functions
  src/data_types/tensor.hpp
  src/geometryXVx/rhs/collisions_utils.hpp
  src/interpolation/Lagrange.hpp
  src/matrix_tools/matrix_corner_block.cpp
  src/matrix_tools/matrix_utils.hpp
  src/multipatch/data_types/types.hpp
  src/multipatch/utils/multipatch_math_tools.hpp
  src/pde_solvers/polarpoissonlikesolver.hpp
  src/quadrature/gauss_legendre_integration.hpp
  src/speciesinfo/species_init.cpp
  src/speciesinfo/species_init.hpp
  src/utils/ddc_helper.hpp
Labels: documentation, Ready to review

#197 Change input/output grid name for compatibility with netCDF
  src/io/input.hpp
Labels: Ready to merge

#127 Replace Matrix2x2 types with DTensor type for Jacobian computations
  src/data_types/tensor.hpp
  src/geometryRTheta/advection/bsl_advection_rtheta.hpp
  src/geometryRTheta/advection_field/advection_field_rtheta.hpp
  src/mapping/cartesian_to_circular.hpp
  src/mapping/circular_to_cartesian.hpp
  src/mapping/combined_mapping.hpp
  src/mapping/czarny_to_cartesian.hpp
  src/mapping/discrete_to_cartesian.hpp
  src/mapping/inv_jacobian_o_point.hpp
  src/mapping/inverse_jacobian_matrix.hpp
  src/mapping/mapping_tools.hpp
  src/mapping/vector_mapper.hpp
  src/math_tools/math_tools.hpp
  tests/geometryRTheta/advection_field_rtheta/advection_field_gtest.cpp
  tests/geometryRTheta/advection_rtheta/test_cases.hpp
  tests/interpolation/polar_bsplines.cpp
  tests/interpolation/polar_splines.cpp
  tests/mapping/mapping_jacobian.cpp
  tests/mapping/mapping_jacobian_matrix_coef.cpp
  tests/mapping/pseudo_cartesian_jacobian_matrix.cpp
  tests/mapping/refined_discrete_mapping.cpp
Labels: Ready to review

#208 Move doc folder into docs/latex
  .github/workflows/static_analyses.yml
  .typos.toml
  docs/latex/Landau_BOT/Figures/Fig_BoT_DispRel.png
  docs/latex/Landau_BOT/Figures/Fig_Feq_BoT.png
  docs/latex/Landau_BOT/Figures/Fig_Landau_DispRel.png
  docs/latex/Landau_BOT/Figures/Fig_Landau_poles.png
  docs/latex/Landau_BOT/Figures/Fig_Landau_poles_zoom.png
  docs/latex/Landau_BOT/Figures/Fig_contourLandau.png
  docs/latex/Landau_BOT/Figures/Fig_contourZ.png
  docs/latex/Landau_BOT/Figures/Fig_island.png
  docs/latex/Landau_BOT/VOICE_Landau_BumpOnTail.pdf
  docs/latex/Landau_BOT/VOICE_Landau_BumpOnTail.tex
  docs/latex/distribution_function.txt
  docs/latex/geometry5D/collisions/Figures/2_species_temperature.PNG
  docs/latex/geometry5D/collisions/Figures/2_species_velocities.PNG
  docs/latex/geometry5D/collisions/Figures/isotropisation.PNG
  docs/latex/geometry5D/collisions/Gysela_collision.pdf
  docs/latex/geometry5D/collisions/Gysela_collision.tex
  docs/latex/geometryXVx/rhs/collisions_intra_inter.pdf
  docs/latex/geometryXVx/rhs/collisions_intra_inter.tex
  docs/latex/geometryXVx/rhs/kinetic_source.pdf
  docs/latex/geometryXVx/rhs/kinetic_source.tex
  docs/latex/geometryXVx/rhs/krook_source.pdf
  docs/latex/geometryXVx/rhs/krook_source.tex
  docs/latex/geometryXVx/rhs/library.bib
  docs/latex/geometryXVx/rhs/mask_tanh.pdf
  docs/latex/geometryXVx/rhs/mask_tanh.tex
  docs/latex/visualise_bsplines.py
Labels: documentation, Ready to review

#210 Generalise MetricTensorEvaluator to ND
  src/mapping/metric_tensor_evaluator.hpp
Labels: Ready to merge

#160 Create a SplinePartialDerivative2D class
  src/math_tools/README.md
  src/math_tools/spline_2d_partial_derivative.hpp
  src/math_tools/spline_builder_2d_cache.hpp
  tests/math_tools/test_partial_derivatives.cpp
Labels: Ready to merge

#202 Add documentation about covariant coordinate changes
  docs/mathematical_and_physical_conventions.md
Labels: documentation, Ready to merge

#211 Remove unused/unnecessary files
  prepare.gyselalibxx.sh
  voicexx.imp
Labels: Ready to merge

#212 Add missing MPI error
  simulations/geometryXYVxVy/landau/params.yaml.hpp
  src/mpi_parallelisation/mpilayout.hpp
Labels: Ready to merge

#205 Add norm operators
  src/data_types/vector_field_mem.hpp
  src/mapping/metric_tensor_evaluator.hpp
  src/math_tools/math_tools.hpp
  tests/math_tools/CMakeLists.txt
  tests/math_tools/test_math_tools.cpp
Labels: Ready to merge

#214 Port (r,theta) BSL advection to GPU
  src/geometryRTheta/advection/bsl_advection_rtheta.hpp
  src/geometryRTheta/advection/iadvection_rtheta.hpp
  tests/geometryRTheta/advection_field_rtheta/advection_field_gtest.cpp
Labels: Ready to review, GPU

#218 Update typos config file
  .typos.toml
Labels: Ready to merge

#215 Update the documentation to include the formula for the divergence operator
  docs/mathematical_and_physical_conventions.md
Labels: Ready to merge

#193 MkDocs Integration into Gyselalibxx
  .github/workflows/deploy.yml
  .github/workflows/static_analyses.yml
  .gitignore
  .markdownlint.json
  .typos.toml
  CMakeLists.txt
  README.md
  bin/ci_tools/markdown_linter.py
  docs/CMakeLists.txt
  docs/README.md
  docs/development/Adding_docs.md
  docs/development/Using_git.md
  docs/development/developer_FAQ.md
  docs/first_steps/DDC_in_gyselalibxx.md
  docs/first_steps/getting_started.md
  docs/first_steps/install.md
  docs/images/curvilinear_coordinates_contravariant_covariant_bases.png
  docs/images/curvilinear_coordinates_def.png
  docs/images/logo_big.png
  docs/jscript/katex.js
  docs/jscript/mathjax.js
  docs/latex/collisions/Figures/2_species_temperature.PNG
  docs/latex/collisions/Figures/2_species_velocities.PNG
  docs/latex/collisions/Figures/isotropisation.PNG
  docs/latex/collisions/Gysela_collision.pdf
  docs/latex/collisions/Gysela_collision.tex
  docs/latex/geometryXVx/rhs/collisions_intra_inter.pdf
  docs/latex/geometryXVx/rhs/collisions_intra_inter.tex
  docs/mkdocs.yml
  docs/prepare_mkdocs.py
  docs/readme_to_mkdocs.py
  docs/requirements.txt
  docs/standards/CODING_STANDARD.md
  docs/standards/mathematical_and_physical_conventions.md
  docs/template/layout.xml
  docs/troubleshooting/Common_compilation_problems.md
  simulations/geometryXVx/README.md
  src/advection/README.md
  src/collisions/README.md
  src/geometryRTheta/advection/README.md
  src/geometryRTheta/advection_field/README.md
  src/geometryXVx/boltzmann/README.md
  src/io/input.hpp
  src/mapping/combined_mapping.hpp
  src/matrix_tools/matrix_centre_block.hpp
  src/multipatch/connectivity/README.md
  src/multipatch/spline/README.md
  toolchains/README.md
Labels: documentation, Ready to merge

#209 Add a gradient operator
  src/data_types/vector_field.hpp
  src/mapping/metric_tensor_evaluator.hpp
  src/math_tools/gradient.hpp
  tests/math_tools/CMakeLists.txt
  tests/math_tools/test_gradient.cpp
Labels: Ready to merge

#223 Improve CI automisation
  .github/actions/duplicate_check/action.yml
  .github/actions/set_pr_status/action.yml
  .github/workflows/check_required_test_result.yml
  .github/workflows/clean_up.yml
  .github/workflows/cpu_tests.yml
  .github/workflows/draft_flags.yml
  .github/workflows/flag_checks.yml
  .github/workflows/gpu_tests.yml
  .github/workflows/review_react.yml
  .github/workflows/static_analyses.yml
  .github/workflows/tests.yml
Labels: Ready to merge

#224 Add a templated function to compute the components of the inverse Jacobian matrix
  src/mapping/circular_to_cartesian.hpp
  src/mapping/combined_mapping.hpp
  src/mapping/czarny_to_cartesian.hpp
  src/mapping/inverse_jacobian_matrix.hpp
  src/mapping/mapping_tools.hpp
  tests/mapping/mapping_jacobian_matrix_coef.cpp
Labels: Ready to merge

#219 Update doc on coordinate sytems
  docs/standards/mathematical_and_physical_conventions.md
Labels: documentation, Ready to review, Ready to merge

#228 Add a Levi-Civita tensor type
  src/data_types/static_tensors.hpp
  src/data_types/tensor_index_tools.hpp
  src/utils/type_seq_tools.hpp
  tests/data_types/geometry_tensor.hpp
  tests/data_types/tensor.cpp
Labels: Ready to review

#226 Use Gyselalib++ instead of gyselalibxx everywhere
  .typos.toml
  README.md
  docs/development/Using_git.md
  docs/first_steps/DDC_in_gyselalibxx.md
  docs/first_steps/getting_started.md
  src/collisions/README.md
Labels: Ready to merge
