Repository gyselax/gyselalibxx, pull requests merged in 2025-02, with the labels that each got.

#87 Remove compilation of Kokkos tools
  CMakeLists.txt
  simulations/geometryRTheta/diocotron/diocotron.cpp
  simulations/geometryVparMu/collisions/test_collSpVparMu.cpp
  simulations/geometryXVx/bump_on_tail/bumpontail_fem_uniform.cpp
  simulations/geometryXVx/bump_on_tail/bumpontail_fft.cpp
  simulations/geometryXVx/landau/landau_fem_uniform.cpp
  simulations/geometryXVx/landau/landau_fft.cpp
  simulations/geometryXY/guiding_center/guiding_center.cpp
  simulations/geometryXYVxVy/landau/landau4d_fft.cpp
Labels: Ready to merge

#91 Be more explicit about clang-format version
  bin/indent
Labels: Ready to review

#97 CI improvements
  .github/workflows/clean_up.yml
  .github/workflows/draft_flags.yml
  .github/workflows/flag_checks.yml
  .github/workflows/gpu_tests.yml
  .github/workflows/static_analyses.yml
  .github/workflows/tests.yml
Labels: Ready to review

#84 Readme src/mapping
  src/mapping/README.md
Labels: documentation, Ready to review

#95 Fix CMAKE_TOOLCHAIN_FILE cmake variable
  .github/actions/build_code/action.yml
  .github/actions/run_tests/action.yml
  .github/workflows/tests.yml
Labels: bug

#88 Port the geometryRTheta interpolator to gpu
  simulations/geometryRTheta/diocotron/diocotron.cpp
  simulations/geometryRTheta/vortex_merger/vortex_merger.cpp
  src/geometryRTheta/advection/bsl_advection_rp.hpp
  src/geometryRTheta/interpolation/i_interpolator_2d_rp.hpp
  src/geometryRTheta/interpolation/spline_interpolator_2d_rp.hpp
  src/math_tools/math_tools.hpp
  tests/geometryRTheta/2d_spline_interpolator/2d_spline_interpolator.cpp
  tests/geometryRTheta/advection_2d_rp/advection_all_tests.cpp
  tests/geometryRTheta/advection_2d_rp/advection_selected_test.cpp
  tests/geometryRTheta/advection_field_rp/advection_field_gtest.cpp
  tests/mapping/mapping_jacobian_matrix_coef.cpp
  toolchains/v100.persee/debug_toolchain.cmake
Labels: Ready to merge

#77 Add tools for tensors
  src/data_types/tensor_index_tools.hpp
  src/data_types/vector_index_tools.hpp
  src/utils/type_seq_tools.hpp
  tests/data_types/CMakeLists.txt
  tests/data_types/tensor.cpp
Labels: Ready to review

#110 Prepare r,theta advection tests for GPU
  tests/geometryRTheta/advection_2d_rp/advection_all_tests.cpp
  tests/geometryRTheta/advection_2d_rp/advection_selected_test.cpp
  tests/geometryRTheta/advection_2d_rp/advection_simulation_utils.hpp
  tests/geometryRTheta/advection_2d_rp/test_cases.hpp
  tests/geometryRTheta/advection_field_rp/CMakeLists.txt
  tests/geometryRTheta/advection_field_rp/advection_field_gtest.cpp
  tests/geometryRTheta/advection_field_rp/test_cases_adv_field.hpp
Labels: Ready to merge

#85 Use new vector type in existing code
  .github/actions/test_filter/action.yml
  src/data_types/tensor.hpp
  src/data_types/vector_field_common.hpp
  src/geometryRTheta/geometry/geometry.hpp
  src/mapping/geometry_pseudo_cartesian.hpp
  src/mapping/vector_mapper.hpp
  src/math_tools/l_norm_tools.hpp
  src/timestepper/itimestepper.hpp
  src/utils/ddc_aliases.hpp
  tests/data_types/field.cpp
  tests/data_types/tensor.cpp
  tests/mapping/metric_tensor.cpp
  tests/math_tools/test_lnorm_tools.cpp
  tests/multipatch/geometries/2patches_2d_non_periodic.hpp
  tests/multipatch/geometries/2patches_2d_onion_shape.hpp
  tests/timestepper/crank_nicolson_2d_mixed.cpp
  tests/timestepper/euler_2d_mixed.cpp
  tests/timestepper/runge_kutta_2d.cpp
  tests/timestepper/runge_kutta_2d_mixed.cpp
Labels: Ready to merge

#112 Improve compilation error output
  src/data_types/vector_field.hpp
  src/data_types/vector_field_mem.hpp
Labels: Ready to review

#113 Use Vector type in Polar Poisson solver
  src/mapping/metric_tensor.hpp
  src/math_tools/math_tools.hpp
  src/pde_solvers/polarpoissonlikesolver.hpp
  tests/multipatch/geometries/5patches_figure_of_eight.hpp
  tests/multipatch/geometries/9patches_2d_periodic_strips_uniform.hpp
  tests/multipatch/geometries/physical_geometry.hpp
Labels: Ready to review

#119 Update multipatch_spline_evaluator.cpp
  tests/multipatch/spline/multipatch_spline_evaluator.cpp
Labels: Ready to review

#118 Update Persee environment with Kokkos 4.5.1, Kokkos Kernels 4.5.1 and Kokkos-fft 0.2.1
  tests/mapping/mapping_jacobian_matrix_coef.cpp
  toolchains/a100.leonardo.spack/toolchain.cmake
  toolchains/cicd_default_toolchain.cmake
  toolchains/v100.persee/debug_toolchain.cmake
  toolchains/v100.persee/toolchain.cmake
  toolchains/v100.ruche/toolchain.cmake
Labels: Ready to merge

#128 Renamed OT into OtherType part 2
  src/multipatch/data_types/multipatch_type.hpp
Labels: Ready to review

#129 Improve rounding errors in uniform interpolation point initialisation
  src/utils/non_uniform_interpolation_points.hpp
Labels: Ready to review

#130 Added readme to geometryXYVxVy/initialization folder
  src/geometryXYVxVy/README.md
  src/geometryXYVxVy/initialization/README.md
Labels: Ready to review

#117 Replace Matrix2x2 types with DTensor type for metric tensor computations
  src/data_types/tensor_index_tools.hpp
  src/geometryRTheta/advection/bsl_advection_rp.hpp
  src/geometryRTheta/advection_field/advection_field_rp.hpp
  src/mapping/README.md
  src/mapping/metric_tensor_evaluator.hpp
  src/pde_solvers/polarpoissonlikesolver.hpp
  tests/geometryRTheta/advection_field_rp/advection_field_gtest.cpp
  tests/mapping/CMakeLists.txt
  tests/mapping/metric_tensor_evaluator.cpp
Labels: Ready to merge

#120 Add a spell checker
  .github/workflows/static_analyses.yml
  .typos.toml
  src/geometryXYVxVy/initialisation/README.md
Labels: Ready to merge

#116 Non-orthogonal case for the gradient in the advection field RTheta
  src/geometryRTheta/advection/README.md
  src/geometryRTheta/advection/bsl_advection_rp.hpp
  src/geometryRTheta/advection/iadvection_rp.hpp
  src/geometryRTheta/advection_field/README.md
  src/geometryRTheta/advection_field/advection_field_rp.hpp
  src/geometryRTheta/time_solver/README.md
  tests/geometryRTheta/advection_field_rp/advection_field_gtest.cpp
Labels: Ready to merge

#136 Add post-process directory to list of spell-checked directories
  .github/workflows/static_analyses.yml
Labels: Ready to merge

#133 Add an omp toolchain for Persee
  toolchains/xeon.persee/debug_toolchain.cmake
  toolchains/xeon.persee/environment.sh
  toolchains/xeon.persee/toolchain.cmake
Labels: Ready to merge
