Repository gyselax/gyselalibxx, pull requests merged in 2025-04, with the labels that each got.

#233 Store advection field in Vector not Coordinate
  .github/workflows/cpu_tests.yml
  .github/workflows/draft_flags.yml
  src/geometryRTheta/advection/bsl_advection_rtheta.hpp
  src/geometryRTheta/advection/iadvection_rtheta.hpp
  src/geometryRTheta/advection_field/advection_field_rtheta.hpp
  tests/geometryRTheta/advection_field_rtheta/advection_field_gtest.cpp
  tests/geometryRTheta/advection_rtheta/advection_simulation_utils.hpp
  tests/geometryRTheta/advection_rtheta/test_cases.hpp
Labels: Ready to merge

#222 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation_issue.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/installation_issue.yml
  .github/ISSUE_TEMPLATE/performance_issue.yml
  .github/ISSUE_TEMPLATE/refactoring.yml
Labels: Ready to merge

#241 Clean up mapping tools
  src/mapping/combined_mapping.hpp
  src/mapping/inverse_jacobian_matrix.hpp
  src/mapping/mapping_tools.hpp
  src/mapping/metric_tensor_evaluator.hpp
  src/pde_solvers/polarpoissonlikesolver.hpp
  src/quadrature/volume_quadrature_nd.hpp
  tests/mapping/mapping_jacobian.cpp
  tests/mapping/mapping_jacobian_matrix_coef.cpp
  tests/mapping/refined_discrete_mapping.cpp
Labels: Ready to merge

#245 Add a fence before communication
  src/geometryXYVxVy/poisson/mpichargedensitycalculator.cpp
Labels: Ready to merge

#238 Batch the polar spline foot finder
  src/advection/ipolar_foot_finder.hpp
  src/advection/spline_polar_foot_finder.hpp
Labels: Ready to merge

#246 Correct cartesian to circular equations
  src/mapping/cartesian_to_circular.hpp
  tests/mapping/CMakeLists.txt
  tests/mapping/mapping_analytical_inverse.cpp
  tests/mapping/mapping_jacobian.cpp
  tests/mapping/mapping_jacobian_matrix_coef.cpp
Labels: Ready to merge

#236 Adapt `EdgeTransformation` operator to onion geometry.
  src/multipatch/connectivity/edge_transformation.hpp
  tests/multipatch/connectivity/CMakeLists.txt
  tests/multipatch/connectivity/coord_transformation.cpp
  tests/multipatch/connectivity/coord_transformation_periodic.cpp
  tests/multipatch/connectivity/index_transformation_non_uniform.cpp
  tests/multipatch/connectivity/index_transformation_non_uniform_periodic.cpp
  tests/multipatch/connectivity/index_transformation_uniform.cpp
  tests/multipatch/connectivity/index_transformation_uniform_periodic.cpp
Labels: Ready to review, Ready to merge

#248 Split CPU and GPU workflows
  .github/actions/set_pr_status/action.yml
  .github/workflows/cpu_tests.yml
  .github/workflows/gpu_tests.yml
  .github/workflows/static_analyses.yml
  .github/workflows/tests.yml
Labels: Ready to review, Ready to merge

#234 Generalise polar advection to work with multiple geometries
  bin/ci_tools/markdown_linter.py
  docs/first_steps/DDC_in_gyselalibxx.md
  simulations/geometryRTheta/diocotron/CMakeLists.txt
  simulations/geometryRTheta/diocotron/diocotron.cpp
  simulations/geometryRTheta/vortex_merger/CMakeLists.txt
  simulations/geometryRTheta/vortex_merger/vortex_merger.cpp
  src/advection/README.md
  src/advection/bsl_advection_polar.hpp
  src/advection/spline_polar_foot_finder.hpp
  src/geometryRTheta/CMakeLists.txt
  src/geometryRTheta/README.md
  src/geometryRTheta/advection/CMakeLists.txt
  src/geometryRTheta/advection/README.md
  src/geometryRTheta/advection/iadvection_rtheta.hpp
  src/geometryRTheta/advection_field/README.md
  src/geometryRTheta/time_solver/CMakeLists.txt
  src/geometryRTheta/time_solver/bsl_predcorr.hpp
  src/geometryRTheta/time_solver/bsl_predcorr_second_order_explicit.hpp
  src/geometryRTheta/time_solver/bsl_predcorr_second_order_implicit.hpp
  src/timestepper/README.md
  tests/geometryRTheta/advection_field_rtheta/CMakeLists.txt
  tests/geometryRTheta/advection_field_rtheta/advection_field_gtest.cpp
  tests/geometryRTheta/advection_field_rtheta/test_cases_adv_field.hpp
  tests/geometryRTheta/advection_rtheta/CMakeLists.txt
  tests/geometryRTheta/advection_rtheta/README.md
  tests/geometryRTheta/advection_rtheta/advection_all_tests.cpp
  tests/geometryRTheta/advection_rtheta/advection_selected_test.cpp
  tests/geometryRTheta/advection_rtheta/advection_simulation_utils.hpp
  tests/geometryRTheta/advection_rtheta/test_cases.hpp
Labels: Ready to review, Ready to merge

#251 Update gitlab documentation CI
  .github/workflows/gpu_tests.yml
  .gitlab-ci.yml
  bin/ci_tools/gyselalib_static_analysis.py
Labels: Ready to review

#203 Add coverage monitoring
  .github/actions/test_filter/action.yml
  .github/workflows/cpu_tests.yml
  README.md
  codecov.yml
  tests/geometryXVx/CMakeLists.txt
  toolchains/docker.gyselalibxx_env/tests_coverage_toolchain.cmake
Labels: Ready to review

#253 Fix DDC related links
  docs/first_steps/DDC_in_gyselalibxx.md
  docs/standards/CODING_STANDARD.md
Labels: Ready to merge

#244 Implement partial derivatives with boundary values
  src/math_tools/README.md
  src/math_tools/central_fdm_partial_derivatives_with_boundary_values.hpp
  tests/math_tools/test_partial_derivatives.cpp
Labels: Ready to merge

#254 Add a Landau damping tutorial
  docs/first_steps/landau_damping_tutorial.md
  docs/mkdocs.yml
Labels: documentation, Ready to merge

#240 Add a ToroidalToCylindrical coordinate change operator
  src/mapping/README.md
  src/mapping/metric_tensor_evaluator.hpp
  src/mapping/toroidal_to_cylindrical.hpp
  tests/mapping/geometry_mapping_tests.hpp
  tests/mapping/mapping_jacobian.cpp
Labels: Ready to merge

#255 Fix some CI bugs
  .github/actions/set_pr_status/action.yml
  .github/workflows/check_required_test_result.yml
Labels: Ready to review, Ready to merge

#258 Increase timeout for polar Poisson tests
  tests/geometryRTheta/polar_poisson/CMakeLists.txt
Labels: Ready to review

#250 Base CI scripts off devel not main
  .github/actions/duplicate_check/action.yml
  .github/workflows/cpu_tests.yml
  .github/workflows/deploy.yml
  .github/workflows/draft_flags.yml
  .github/workflows/flag_checks.yml
  .github/workflows/gpu_tests.yml
  README.md
  bin/create_private_fork
  bin/pre-push
  bin/public_mirror
  docs/development/Using_git.md
  docs/first_steps/landau_damping_tutorial.md
  src/geometryXVx/rhs/collisions_inter.hpp
  src/geometryXVx/rhs/collisions_intra.hpp
  src/geometryXVx/rhs/kinetic_source.hpp
  src/geometryXVx/rhs/krook_source_adaptive.hpp
Labels: Ready to merge

#261 Ensure coverage tests run correctly on devel branch
  README.md
  bin/ci_tools/markdown_linter.py
  src/pde_solvers/polarpoissonlikesolver.hpp
  tests/geometryRTheta/polar_poisson/CMakeLists.txt
  tests/geometryRTheta/polar_poisson/test_poisson.py
Labels: Ready to merge

#263 Add a CONTRIBUTING file to the docs
  docs/CONTRIBUTING.md
  docs/mkdocs.yml
Labels: Ready to merge

#272 Add x0 and y0 parameters to circular and czarny coordinate change operators
  .github/actions/test_filter/action.yml
  src/mapping/cartesian_to_circular.hpp
  src/mapping/cartesian_to_czarny.hpp
  src/mapping/circular_to_cartesian.hpp
  src/mapping/czarny_to_cartesian.hpp
  tests/geometryRTheta/advection_rtheta/advection_all_tests.cpp
  tests/geometryRTheta/polar_poisson/polarpoissonfemsolver.cpp
  tests/geometryRTheta/polar_poisson/test_cases.hpp
Labels: Ready to review, Ready to merge
